import Link from "next/link";
import { ArrowRight, Building2, CheckCircle2, Mail, MapPin, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";
import { Logo } from "@/components/brand/Logo";

type PageKind = "contact" | "privacy" | "terms";

const privacySections = [
  ["Information PerkJoy handles", "Company account details, employee work information, birthday month and day, hire dates, celebration preferences, reward records, and local-order details needed to provide the service."],
  ["How information is used", "To remember eligible moments, personalize recommendations, coordinate approved rewards, support company administrators, protect the service, and improve reliability."],
  ["Employee choice and privacy", "Employees can share Celebration Profile preferences through secure links. Recommendations-only preferences are used to produce suggestions without revealing raw answers to unauthorized managers."],
  ["Service providers", "PerkJoy may use carefully selected infrastructure, payment, reward, email, analytics, and fulfillment providers. Providers receive only the information required for their role."],
  ["Retention and security", "PerkJoy uses access controls, organization boundaries, audit logs, and secure server-side integrations. Data is retained only as needed for the service, legal obligations, and legitimate business records."],
  ["Your choices", "Company administrators can update team data and notification preferences. Employees may ask their employer or PerkJoy about personal information associated with a Celebration Profile."],
];

const termsSections = [
  ["Using PerkJoy", "You must be authorized to create or manage an organization account and provide accurate company information. Keep credentials secure and use employee information only for legitimate workplace celebrations."],
  ["Subscriptions and payment", "A credit card is required for paid service. SaaS subscription charges are separate from employee rewards, local orders, marketplace fees, and Concierge services."],
  ["Rewards and approvals", "Companies control reward rules, budgets, and approvals. Development and demo environments do not send production gift cards. Physical recommendations require employer approval before purchase."],
  ["Local fulfillment", "Local product availability, timing, substitutions, delivery windows, and vendor acceptance can vary. PerkJoy will communicate material changes and may suggest reasonable alternatives."],
  ["Acceptable use", "Do not misuse the service, access another organization’s data, upload unlawful content, interfere with security, or use employee information for unrelated purposes."],
  ["Service changes", "PerkJoy may improve, add, or retire features. Material changes affecting paid service will be communicated through reasonable channels."],
  ["Disclaimers and responsibility", "PerkJoy is provided subject to applicable law. Each company remains responsible for employment decisions, reward policies, tax treatment, and the accuracy of employee data it provides."],
];

export function PublicInfoPage({ kind }: { kind: PageKind }) {
  if (kind === "contact") return <main className="public-info-page contact-page"><PublicNav /><section className="contact-hero"><span><MessageCircle /></span><small>CONTACT PERKJOY</small><h1>Let&apos;s make appreciation easier.</h1><p>Questions about plans, Philadelphia fulfillment, or bringing PerkJoy to your team? We&apos;re ready to help.</p></section><section className="contact-options"><article><span><Building2 /></span><small>SALES</small><h2>Bring PerkJoy to your company.</h2><p>Tell us your team size, locations, and how you celebrate today.</p><a className="button button-primary" href="mailto:hello@perkjoy.app?subject=PerkJoy%20for%20our%20company">Contact sales <ArrowRight /></a></article><article><span><Sparkles /></span><small>SUPPORT</small><h2>Need help with your workspace?</h2><p>Get help with employees, rules, approvals, rewards, or billing.</p><a className="button button-secondary" href="mailto:support@perkjoy.app?subject=PerkJoy%20support">Email support <ArrowRight /></a></article><article><span><MapPin /></span><small>LOCAL PARTNERS</small><h2>Philadelphia vendors, say hello.</h2><p>Interested in cakes, treats, flowers, meals, or local experiences?</p><a className="button button-secondary" href="mailto:partners@perkjoy.app?subject=PerkJoy%20local%20partner">Partner with us <ArrowRight /></a></article></section><section className="contact-direct"><Mail /><span><small>GENERAL QUESTIONS</small><b>hello@perkjoy.app</b><p>PerkJoy is being built with care in Philadelphia, Pennsylvania.</p></span></section><PublicFooter /></main>;
  const sections = kind === "privacy" ? privacySections : termsSections; const title = kind === "privacy" ? "Privacy that respects the moment." : "Clear terms for celebrating well."; const intro = kind === "privacy" ? "PerkJoy handles employee celebration information with care. This notice explains the information involved, why it is used, and the choices available." : "These terms explain the ground rules for company accounts, subscriptions, rewards, local fulfillment, and responsible use of PerkJoy.";
  return <main className="public-info-page legal-page"><PublicNav /><header><span>{kind === "privacy" ? <ShieldCheck /> : <CheckCircle2 />}</span><small>{kind === "privacy" ? "PRIVACY NOTICE" : "TERMS OF SERVICE"}</small><h1>{title}</h1><p>{intro}</p><em>Effective August 9, 2026</em></header><div className="legal-layout"><aside><b>On this page</b>{sections.map(([heading], index) => <a href={`#section-${index + 1}`} key={heading}>{index + 1}. {heading}</a>)}<Link href="/contact">Questions? Contact us</Link></aside><article>{sections.map(([heading, body], index) => <section id={`section-${index + 1}`} key={heading}><small>{String(index + 1).padStart(2,"0")}</small><h2>{heading}</h2><p>{body}</p></section>)}<section className="legal-contact"><Mail /><div><h2>Questions or requests</h2><p>Email <a href="mailto:privacy@perkjoy.app">privacy@perkjoy.app</a>. Company administrators should include their organization name so we can route the request safely.</p></div></section></article></div><PublicFooter /></main>;
}

function PublicNav() { return <nav className="public-info-nav"><Link href="/"><Logo /></Link><div><Link href="/#how">How it works</Link><Link href="/#pricing">Pricing</Link><Link href="/login">Sign in</Link><Link className="button button-primary" href="/signup">Start Celebrating</Link></div></nav>; }
function PublicFooter() { return <footer className="public-info-footer"><Link href="/"><Logo inverse /></Link><div><Link href="/contact">Contact</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><span>© 2026 PerkJoy · Philadelphia, PA</span></footer>; }
