"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Building2, DollarSign, LoaderCircle, Package, Pencil, Save, Search, Users, X } from "lucide-react";
import { authenticatedFetch } from "@/lib/supabase/fetch";

type Client = { id: string; name: string; city: string | null; state: string | null; postalCode: string | null; timezone: string; monthlyBudget: number; spentThisMonth: number; remainingBudget: number; employeeCount: number; activeEmployeeCount: number; orderCount: number; totalOrderValue: number; defaultRewardAmount: number; preventAboveBudget: boolean; subscriptionStatus: string; monthlyRecurringRevenue: number };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100);

export function AdminClientManager() {
  const [clients, setClients] = useState<Client[]>([]); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<Client | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { setLoading(true); try { const response = await authenticatedFetch("/api/admin/clients", { cache: "no-store" }); const data = await response.json() as { clients?: Client[]; error?: string }; if (!response.ok) throw new Error(data.error || "Unable to load clients."); setClients(data.clients || []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load clients."); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  const shown = useMemo(() => clients.filter((client) => `${client.name} ${client.city} ${client.state}`.toLowerCase().includes(query.toLowerCase())), [clients, query]);
  const totals = useMemo(() => clients.reduce((sum, item) => ({ budget: sum.budget + item.monthlyBudget, employees: sum.employees + item.employeeCount, orders: sum.orders + item.orderCount }), { budget: 0, employees: 0, orders: 0 }), [clients]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; setSaving(true); setError(""); const form = new FormData(event.currentTarget); const payload = { organizationId: editing.id, name: form.get("name"), city: form.get("city"), state: form.get("state"), postalCode: form.get("postalCode"), timezone: form.get("timezone"), monthlyBudget: Math.round(Number(form.get("monthlyBudget")) * 100), defaultRewardAmount: Math.round(Number(form.get("defaultRewardAmount")) * 100), preventAboveBudget: form.get("preventAboveBudget") === "on" }; try { const response = await authenticatedFetch("/api/admin/clients", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Unable to save client."); setMessage(`${payload.name} was updated.`); setEditing(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save client."); } finally { setSaving(false); } }
  return <div className="admin-client-manager">
    <section className="client-summary"><article><DollarSign /><span><small>Managed monthly budget</small><b>{money(totals.budget)}</b></span></article><article><Users /><span><small>Employees</small><b>{totals.employees}</b></span></article><article><Package /><span><small>Items ordered</small><b>{totals.orders}</b></span></article></section>
    {(error || message) && <p className={`vendor-admin-message ${error ? "error" : "success"}`}>{error || message}</p>}
    <div className="client-toolbar"><div><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search clients…" /></div><span>{shown.length} organizations</span></div>
    {loading ? <p className="vendor-directory-empty"><LoaderCircle className="spin" /> Loading clients…</p> : <section className="client-directory"><header><b>Client</b><b>Available budget</b><b>Employees</b><b>Items ordered</b><b>Subscription</b><b /></header>{shown.map((client) => <article key={client.id}><div><Building2 /><span><b>{client.name}</b><small>{[client.city, client.state].filter(Boolean).join(", ") || "Location pending"}</small></span></div><span><b>{money(client.remainingBudget)}</b><small>{money(client.spentThisMonth)} spent of {money(client.monthlyBudget)}</small></span><span><b>{client.activeEmployeeCount}/{client.employeeCount}</b><small>active / total</small></span><span><b>{client.orderCount}</b><small>{money(client.totalOrderValue)} total value</small></span><span><em>{client.subscriptionStatus}</em><small>{money(client.monthlyRecurringRevenue)} MRR</small></span><button type="button" onClick={() => setEditing(client)}><Pencil /> Edit</button></article>)}</section>}
    {editing && <div className="admin-edit-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setEditing(null); }}><form className="admin-edit-card" onSubmit={save}><header><div><small>CLIENT RECORD</small><h2>Edit {editing.name}</h2></div><button type="button" onClick={() => setEditing(null)}><X /></button></header><div className="vendor-form-grid"><label className="span-2">Company name<input name="name" required defaultValue={editing.name} /></label><label>City<input name="city" defaultValue={editing.city || ""} /></label><label>State<input name="state" maxLength={2} defaultValue={editing.state || ""} /></label><label>Postal code<input name="postalCode" defaultValue={editing.postalCode || ""} /></label><label>Timezone<input name="timezone" required defaultValue={editing.timezone} /></label><label>Monthly budget ($)<input name="monthlyBudget" type="number" min="0" step="0.01" required defaultValue={(editing.monthlyBudget / 100).toFixed(2)} /></label><label>Default reward ($)<input name="defaultRewardAmount" type="number" min="0" step="0.01" required defaultValue={(editing.defaultRewardAmount / 100).toFixed(2)} /></label><div className="vendor-check span-2"><input id="client-budget-lock" name="preventAboveBudget" type="checkbox" defaultChecked={editing.preventAboveBudget} /><label htmlFor="client-budget-lock">Prevent spending above monthly budget<small>Blocks new spending once this client’s budget is exhausted.</small></label></div></div><footer><button type="button" className="button button-secondary" onClick={() => setEditing(null)}>Cancel</button><button className="button button-primary" disabled={saving}>{saving ? <LoaderCircle className="spin" /> : <Save />} Save client</button></footer></form></div>}
  </div>;
}
