"use client";

import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, LoaderCircle, MessageCircle, Send } from "lucide-react";
import { authenticatedFetch } from "@/lib/supabase/fetch";

type Conversation = { id: string; organizationName: string; subject: string; status: string; priority: string; last_message_at: string; created_at: string };
type Message = { id: string; conversation_id: string; sender_role: string; body: string; created_at: string };

export function AdminSupportInbox() {
  const [conversations, setConversations] = useState<Conversation[]>([]); const [messages, setMessages] = useState<Message[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [filter, setFilter] = useState("active"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function load() { try { const response = await authenticatedFetch("/api/admin/support", { cache: "no-store" }); const data = await response.json() as { conversations?: Conversation[]; messages?: Message[]; error?: string }; if (!response.ok) throw new Error(data.error || "Unable to load support."); setConversations(data.conversations || []); setMessages(data.messages || []); setSelectedId((current) => current || data.conversations?.[0]?.id || null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load support."); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); const interval = window.setInterval(() => void load(), 10000); return () => { window.clearTimeout(timer); window.clearInterval(interval); }; }, []);
  const visible = conversations.filter((item) => filter === "all" || (filter === "active" ? !["resolved", "closed"].includes(item.status) : item.status === filter));
  const selected = conversations.find((item) => item.id === selectedId) || visible[0]; const thread = messages.filter((item) => item.conversation_id === selected?.id);
  async function update(payload: Record<string, unknown>) { if (!selected) return; setBusy(true); setError(""); try { const response = await authenticatedFetch("/api/admin/support", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ conversationId: selected.id, ...payload }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Unable to update conversation."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update conversation."); } finally { setBusy(false); } }
  function reply(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const message = new FormData(form).get("message"); void update({ message }).then(() => form.reset()); }
  return <div className="admin-support-inbox"><div className="support-inbox-toolbar"><div>{["active", "open", "pending", "resolved", "closed", "all"].map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div><span><i /> Polling for replies</span></div>{error && <p className="vendor-admin-message error">{error}</p>}<div className="support-inbox-grid"><aside>{visible.length ? visible.map((item) => <button key={item.id} className={selected?.id === item.id ? "active" : ""} onClick={() => setSelectedId(item.id)}><span><b>{item.organizationName}</b><em data-status={item.status}>{item.status}</em></span><strong>{item.subject}</strong><small>{new Date(item.last_message_at).toLocaleString()}</small></button>) : <div><CheckCircle2 /><p>No conversations in this queue.</p></div>}</aside><section>{selected ? <><header><div><small>{selected.organizationName}</small><h2>{selected.subject}</h2></div><div><select value={selected.priority} onChange={(event) => void update({ priority: event.target.value })}><option value="low">Low priority</option><option value="normal">Normal priority</option><option value="high">High priority</option><option value="urgent">Urgent</option></select><select value={selected.status} onChange={(event) => void update({ status: event.target.value })}><option value="open">Open</option><option value="pending">Pending</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></div></header><div className="admin-support-thread">{thread.map((item) => <article className={item.sender_role} key={item.id}><small>{item.sender_role === "admin" ? "PerkJoy Support" : selected.organizationName}</small><p>{item.body}</p><time>{new Date(item.created_at).toLocaleString()}</time></article>)}</div><form onSubmit={reply}><textarea name="message" required rows={3} maxLength={4000} placeholder="Write a response…" /><button className="button button-primary" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : <Send />} Send reply</button></form></> : <div className="support-empty"><MessageCircle /><h2>Select a conversation</h2><p>Client support messages and their full history will appear here.</p></div>}</section></div></div>;
}
